### PR TITLE
Code changes for deployment on lambda

### PR DESCRIPTION
**Pull request by mundra-ankur**

### CODE REVIEW

**Review by JonahSussman — DISMISSED** [review]
Looks good!

**Comment by JonahSussman** [comment]
I'd remove the config directory and replace it with something that emulates the AWS secret manager so we can run it locally

**Review by chaitanyab2311 — APPROVED** [review]
I think this looks good. We can remove the print statements but for now its fine

**Comment by mundra-ankur** [comment]
> I'd remove the config directory and replace it with something that emulates the AWS secret manager so we can run it locally

I have removed the config dir

**Pull request merged**
